"""Target-runtime facts come from the selected environment, not this process."""

from pathlib import Path

import pytest

from svarog.audit_history.target_python import read_target_python


def test_reads_target_version_and_implementation(tmp_path: Path) -> None:
    environment = tmp_path / "venv"
    environment.mkdir()
    (environment / "pyvenv.cfg").write_text(
        "home = /elsewhere/python\nversion = 3.12.4\nimplementation = CPython\n",
        encoding="utf-8",
    )

    assert read_target_python(environment) == ("cpython", (3, 12, 4))


def _environment(tmp_path: Path, contents: bytes) -> Path:
    environment = tmp_path / "venv"
    environment.mkdir()
    (environment / "pyvenv.cfg").write_bytes(contents)
    return environment


def test_missing_version_is_explicitly_unknown(tmp_path: Path) -> None:
    environment = _environment(tmp_path, b"home = /usr/bin\nimplementation = PyPy\n")
    assert read_target_python(environment) == ("pypy", "unknown")


def test_missing_implementation_is_explicitly_unknown(tmp_path: Path) -> None:
    environment = _environment(tmp_path, b"version = 3.13.1\n")
    assert read_target_python(environment) == ("unknown", (3, 13, 1))


def test_explicit_target_never_falls_back_to_running_python(tmp_path: Path) -> None:
    environment = _environment(tmp_path, b"home = /usr/bin\n")
    assert read_target_python(environment) == ("unknown", "unknown")


def test_target_executable_is_not_needed_or_run(tmp_path: Path) -> None:
    environment = _environment(
        tmp_path,
        b"version = 9.8.7\ncommand = /untrusted/bin/python -m venv\n",
    )
    assert read_target_python(environment) == ("unknown", (9, 8, 7))


def test_config_tolerates_standard_unrelated_fields_comments_and_crlf(tmp_path: Path) -> None:
    environment = _environment(
        tmp_path,
        b"# generated by venv\r\nhome = C:\\Python313\r\n"
        b"include-system-site-packages = false\r\nversion = 3.13.0\r\n",
    )
    assert read_target_python(environment) == ("unknown", (3, 13, 0))


@pytest.mark.parametrize(
    "version", ["3.12", "3.12.1rc1", "3.12.1.0", "03.12.1"]
)
def test_plausible_noncanonical_version_is_explicitly_unknown(
    tmp_path: Path, version: str
) -> None:
    environment = _environment(tmp_path, f"version = {version}\n".encode("utf-8"))
    assert read_target_python(environment) == ("unknown", "unknown")


@pytest.mark.parametrize(
    "version",
    [
        "+3.12.1",
        "3.１２.1",
        "3.12.-1",
        "3.12.1 # note",
        "3.12.99999999999999999999",
    ],
)
def test_noncanonical_version_is_rejected(tmp_path: Path, version: str) -> None:
    environment = _environment(tmp_path, f"version = {version}\n".encode("utf-8"))
    with pytest.raises(ValueError, match="^invalid_target_python$"):
        read_target_python(environment)


@pytest.mark.parametrize(
    "contents",
    [
        b"version = 3.12.1\nversion = 3.12.1\n",
        b"version = 3.12.1\nVERSION = 3.13.0\n",
        b"version = 3.12.1\nimplementation = CPython\nimplementation = PyPy\n",
        b"version = 3.12.1\nnot a key value line\n",
        b"version = 3.12.1\nimplementation = CPython;rm -rf /\n",
        b"version = 3.12.1\nimplementation = \n",
        b"version = 3.12.1\n\xff\n",
    ],
)
def test_malformed_configuration_is_rejected(tmp_path: Path, contents: bytes) -> None:
    environment = _environment(tmp_path, contents)
    with pytest.raises(ValueError, match="^invalid_target_python$"):
        read_target_python(environment)


def test_oversized_configuration_is_rejected(tmp_path: Path) -> None:
    environment = _environment(tmp_path, b"version = 3.12.1\n" + b"#" * 70_000)
    with pytest.raises(ValueError, match="^invalid_target_python$"):
        read_target_python(environment)


def test_missing_configuration_is_rejected(tmp_path: Path) -> None:
    environment = tmp_path / "venv"
    environment.mkdir()
    with pytest.raises(ValueError, match="^invalid_target_python$"):
        read_target_python(environment)


def test_configuration_symlink_cannot_escape_environment(tmp_path: Path) -> None:
    environment = tmp_path / "venv"
    environment.mkdir()
    outside = tmp_path / "outside.cfg"
    outside.write_text("version = 3.12.1\n", encoding="utf-8")
    try:
        (environment / "pyvenv.cfg").symlink_to(outside)
    except (OSError, NotImplementedError):
        pytest.skip("symlink creation unavailable")
    with pytest.raises(ValueError, match="^target_python_escape$"):
        read_target_python(environment)
